### ISSUE TITLE
Grammar check of readme and comments

### ISSUE THREAD

**Issue by Hexagon** [Hexagon/minitz#1]
I don't speak english natively, so a grammar check of readme and code comments in /src would be awesome.

**Comment by danieled-it** [comment]
I'm not a native speaker either but I can give it a shot if you want!

**Comment by Hexagon** [comment]
@danieled-it Any improvements is much appreciated 👍

**Comment by coleenho** [comment]
I'm a native English speaker and I can help contribute if you want help on this.  @danieled-it I'll help review your PR.
